# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
tf.__version__

NameError: name 'tf' is not defined

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(X[list(y).index(61), :])
for v in range(len(X[:, 0])):
    X[v, :][0] = conv(X[v, :][0])

print(X[:20, :])

['SrgMD']
[[12470.0]
 [12490.0]
 [12589.0]
 [12590.0]
 [12691.0]
 [12789.0]
 [12792.0]
 [13196.0]
 [13298.0]
 [13308.0]
 [13309.0]
 [13421.0]
 [13431.0]
 [13432.0]
 [13463.0]
 [13513.0]
 [13518.0]
 [13563.0]
 [13587.0]
 [13592.0]]


In [4]:
print(X)

[[12470.0]
 [12490.0]
 [12589.0]
 ...
 [131215.0]
 [131222.0]
 [131281.0]]


In [5]:
print(y)

[61 69 15 ... 31 31 58]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [8]:
ann = tf.keras.models.Sequential()

NameError: name 'tf' is not defined

### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

NameError: name 'ann' is not defined

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

NameError: name 'ann' is not defined

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=94, activation='sigmoid'))

NameError: name 'ann' is not defined

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

NameError: name 'ann' is not defined

### Training the ANN on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

NameError: name 'ann' is not defined

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [14]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

NameError: name 'ann' is not defined

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [15]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

NameError: name 'ann' is not defined

### Making the Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

NameError: name 'y_pred' is not defined