# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('isBhimpalasi.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
print(X_train)

[[109046.]
 [ 15807.]
 [ 69113.]
 ...
 [ 57522.]
 [ 59218.]
 [102568.]]


In [5]:
print(y_train)

[0 0 1 ... 0 0 0]


In [6]:
print(X_test)

[[101871.]
 [ 85812.]
 [108740.]
 [ 57516.]
 [ 81220.]
 [ 43068.]
 [122578.]
 [ 72306.]
 [ 36891.]
 [ 18641.]
 [ 14690.]
 [ 38631.]
 [ 62308.]
 [ 65686.]
 [ 65762.]
 [ 87578.]
 [ 91115.]
 [ 20878.]
 [ 32011.]
 [ 65358.]
 [111464.]
 [ 38353.]
 [ 22136.]
 [ 90212.]
 [106535.]
 [ 22090.]
 [ 14702.]
 [ 81353.]
 [104706.]
 [ 59013.]
 [108741.]
 [118641.]
 [ 60313.]
 [ 69018.]
 [111468.]
 [119641.]
 [ 85685.]
 [ 70116.]
 [ 57908.]
 [101368.]
 [120871.]
 [ 22111.]
 [ 89865.]
 [ 82086.]
 [ 20752.]
 [ 65315.]
 [ 83468.]
 [ 92086.]
 [ 86321.]
 [ 68461.]
 [120881.]
 [ 32085.]
 [ 56418.]
 [ 68653.]
 [ 35812.]
 [ 31565.]
 [ 46441.]
 [106912.]
 [ 23064.]
 [ 13684.]
 [ 17521.]
 [ 91151.]
 [122568.]
 [ 35925.]
 [ 51986.]
 [108357.]
 [ 81235.]
 [ 21146.]
 [ 22969.]
 [109215.]
 [123573.]
 [ 12569.]
 [128121.]
 [130711.]
 [108737.]
 [108651.]
 [101861.]
 [ 85691.]
 [ 21246.]
 [ 90116.]
 [114690.]
 [130690.]
 [ 68642.]
 [ 86525.]
 [ 69041.]
 [ 63692.]
 [ 24784.]
 [121371.]
 [ 91120.]
 [ 62196.]
 [ 86901.]

In [7]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 

## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train.reshape(-1, 1))
X_test = sc.transform(X_test.reshape(-1, 1))

In [9]:
print(X_train)

[[ 1.13024677]
 [-1.60490325]
 [-0.04118091]
 ...
 [-0.3812009 ]
 [-0.33144903]
 [ 0.94021575]]


In [10]:
print(X_test)

[[ 9.19769379e-01]
 [ 4.48681378e-01]
 [ 1.12127031e+00]
 [-3.81376912e-01]
 [ 3.13975848e-01]
 [-8.05206505e-01]
 [ 1.52720566e+00]
 [ 5.24851925e-02]
 [-9.86407737e-01]
 [-1.52176835e+00]
 [-1.63767025e+00]
 [-9.35365136e-01]
 [-2.40804417e-01]
 [-1.41711368e-01]
 [-1.39481921e-01]
 [ 5.00486684e-01]
 [ 6.04243970e-01]
 [-1.45614634e+00]
 [-1.12956170e+00]
 [-1.51333192e-01]
 [ 1.20117838e+00]
 [-9.43520218e-01]
 [-1.41924312e+00]
 [ 5.77754620e-01]
 [ 1.05658702e+00]
 [-1.42059252e+00]
 [-1.63731823e+00]
 [ 3.17877380e-01]
 [ 1.00293362e+00]
 [-3.37462674e-01]
 [ 1.12129965e+00]
 [ 1.41171444e+00]
 [-2.99327398e-01]
 [-4.39677215e-02]
 [ 1.20129572e+00]
 [ 1.44104927e+00]
 [ 4.44955855e-01]
 [-1.17580805e-02]
 [-3.69877659e-01]
 [ 9.05013960e-01]
 [ 1.47713111e+00]
 [-1.41997649e+00]
 [ 5.67575435e-01]
 [ 3.39379809e-01]
 [-1.45984252e+00]
 [-1.52594589e-01]
 [ 3.79920541e-01]
 [ 6.32728088e-01]
 [ 4.63612805e-01]
 [-6.03072207e-02]
 [ 1.47742446e+00]
 [-1.12739092e+00]
 [-4.1358655

## Training the K-NN model on the Training set

In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 9, metric = 'minkowski', p = 2)
knn.fit(X_train.reshape(-1, 1), y_train.reshape(-1, 1))

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=1000, random_state=0)

## Predicting a new result

In [44]:
def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
print(rfc.predict(sc.transform([[conv('gMP')]])))
print(knn.predict(sc.transform([[conv('gMP')]])))

[0]
[0]


## Predicting the Test set results

In [45]:
y_predknn = knn.predict(X_test)
print(np.concatenate((y_predknn.reshape(len(y_predknn),1), y_test.reshape(len(y_test),1)),1))

y_predrfc = rfc.predict(X_test)
print(np.concatenate((y_predrfc.reshape(len(y_predrfc),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predknn)
print(cm)
accuracy_score(y_test, y_predknn)



[[495   8]
 [ 23   3]]


0.941398865784499

In [47]:
cm = confusion_matrix(y_test, y_predrfc)
print(cm)
accuracy_score(y_test, y_predrfc)

[[472  31]
 [ 15  11]]


0.9130434782608695

## Visualising the Training set results

In [36]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

IndexError: index 1 is out of bounds for axis 1 with size 1

## Visualising the Test set results

In [37]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 0].min() - 1000, stop = X_set[:, 0].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

MemoryError: Unable to allocate 106. GiB for an array with shape (120459, 118479) and data type float64