# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [32]:
import numpy as np
import pandas as pd

## Importing the dataset

In [33]:
dataset = pd.read_csv('mldata.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ym = le.fit_transform(y)
print(ym[:20])
print(list(ym).index(61))
for v in range(len(X[:, 0])):
    X[v, :][0] = conv(X[v, :][0])

print(X[:20, :])


[28 23 10 19 31 43 72  3 59 38 45  6 81  0 26 73  3 13 20 59]
307
[[11370.0]
 [11364.0]
 [11342.0]
 [11535.0]
 [11572.0]
 [11590.0]
 [11592.0]
 [11578.0]
 [11579.0]
 [11631.0]
 [11658.0]
 [11691.0]
 [11906.0]
 [12064.0]
 [12086.0]
 [12084.0]
 [12287.0]
 [12306.0]
 [12296.0]
 [12302.0]]


## Splitting the dataset into the Training set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, ym, test_size = 0.05, random_state = 0)

In [35]:
print(X_train)

[[121146.0]
 [56386.0]
 [75901.0]
 ...
 [89125.0]
 [75721.0]
 [79897.0]]


In [36]:
print(y_train)

[12 27 75 ... 15 62 74]


In [37]:
print(X_test)

[[118588.0]
 [63871.0]
 [66570.0]
 [87891.0]
 [119857.0]
 [118731.0]
 [35864.0]
 [105712.0]
 [92858.0]
 [42301.0]
 [72208.0]
 [119896.0]
 [50874.0]
 [52208.0]
 [109118.0]
 [112691.0]
 [89684.0]
 [108435.0]
 [12470.0]
 [81208.0]
 [120633.0]
 [105358.0]
 [108748.0]
 [128581.0]
 [53511.0]
 [97525.0]
 [43661.0]
 [53442.0]
 [16580.0]
 [56924.0]
 [11658.0]
 [102084.0]
 [58431.0]
 [51579.0]
 [71358.0]
 [88743.0]
 [87378.0]
 [11278.0]
 [52964.0]
 [30113.0]
 [122018.0]
 [39092.0]
 [95653.0]
 [65798.0]
 [73130.0]
 [53865.0]
 [127086.0]
 [43075.0]
 [58353.0]
 [39210.0]
 [57310.0]
 [98648.0]
 [105725.0]
 [80881.0]
 [51365.0]
 [28029.0]
 [97979.0]
 [51636.0]
 [66368.0]
 [128880.0]
 [123468.0]
 [78656.0]
 [103920.0]
 [64229.0]
 [84371.0]
 [87321.0]
 [58641.0]
 [71578.0]
 [13511.0]
 [120903.0]
 [12490.0]
 [22871.0]
 [90633.0]
 [43470.0]
 [106322.0]
 [79121.0]
 [98562.0]
 [36591.0]
 [107252.0]
 [21968.0]
 [14693.0]
 [71146.0]
 [31342.0]
 [92063.0]
 [26846.0]
 [40753.0]
 [81631.0]
 [59019.0]
 [81658.0]

In [38]:
print(y_test)

[27 27 56 68 68 70  8 13 72 41 70 37 50 35 17  7 37  8 60 22 28 19 50 72
 24 74  8 34 53 34 45 73  8 59 75 50 70 74 20 10 23 44 57  9 31 27 56 66
 72 51 31 46 62 22 81 59 48 38 28 22 46 22 51 20  8 70  8  3 81 80 69  3
 80  0 80 49 68  8 62 37 10 12 10 28 10 66 38 68 45 72 27 81 22 59  7 49
 12 31 70 10  3 17  1 62  7 64 35 28 26 69 37 70 60 68 69 28 34 72 62 15
 60  2 34 23  0 50 17 12 56 24 40 50 28 30 24 44  8 51 34  8 30 38 49 81
 45 80 15 53 59 30 49 32 66 22 38 34  3 45]


## Feature Scaling

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train.reshape(-1, 1))
X_test = sc.transform(X_test.reshape(-1, 1))

In [40]:
print(X_train)

[[ 1.44460053]
 [-0.42209099]
 [ 0.14042422]
 ...
 [ 0.52160286]
 [ 0.13523576]
 [ 0.25560796]]


In [41]:
print(X_test)

[[ 1.37086679]
 [-0.20633765]
 [-0.12853962]
 [ 0.4860331 ]
 [ 1.40744541]
 [ 1.37498873]
 [-1.01363273]
 [ 0.99971917]
 [ 0.62920569]
 [-0.82808775]
 [ 0.03397438]
 [ 1.40856957]
 [-0.58097307]
 [-0.54252084]
 [ 1.0978963 ]
 [ 1.20088717]
 [ 0.5377159 ]
 [ 1.07820899]
 [-1.68795919]
 [ 0.29339723]
 [ 1.42981342]
 [ 0.9895152 ]
 [ 1.08723114]
 [ 1.65891262]
 [-0.50496218]
 [ 0.76373085]
 [-0.78888607]
 [-0.50695108]
 [-1.56948942]
 [-0.40658327]
 [-1.71136489]
 [ 0.89514293]
 [-0.36314435]
 [-0.56065161]
 [ 0.00947333]
 [ 0.5105918 ]
 [ 0.471246  ]
 [-1.7223183 ]
 [-0.52072932]
 [-1.17940393]
 [ 1.46973572]
 [-0.9205864 ]
 [ 0.7097709 ]
 [-0.15079234]
 [ 0.06055081]
 [-0.49475821]
 [ 1.61581961]
 [-0.80577738]
 [-0.36539268]
 [-0.91718508]
 [-0.39545691]
 [ 0.79610106]
 [ 1.00009389]
 [ 0.28397153]
 [-0.56682011]
 [-1.23947473]
 [ 0.77681729]
 [-0.5590086 ]
 [-0.13436223]
 [ 1.66753123]
 [ 1.51153162]
 [ 0.21983644]
 [ 0.94806519]
 [-0.19601839]
 [ 0.38456994]
 [ 0.46960299]
 [-0.35709

## Training the K-NN model on the Training set

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1, metric = 'minkowski', p = 2)
knn.fit(X_train.reshape(-1, 1), y_train.reshape(-1, 1))

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting a new result

In [43]:

def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
phrase = input('Please enter a phrase: ')
print(rfc.predict(sc.transform([[conv(phrase)]])))
print(y[list(ym).index(int(rfc.predict(sc.transform([[conv(phrase)]]))))])

[31]
 Hameer


## Predicting the Test set results

In [44]:
y_predknn = knn.predict(X_test)
print(np.concatenate((y_predknn.reshape(len(y_predknn),1), y_test.reshape(len(y_test),1)),1))

y_predrfc = rfc.predict(X_test)
print(np.concatenate((y_predrfc.reshape(len(y_predrfc),1), y_test.reshape(len(y_test),1)),1))

[[27 27]
 [27 27]
 [53 56]
 [68 68]
 [68 68]
 [49 70]
 [19  8]
 [65 13]
 [32 72]
 [29 41]
 [49 70]
 [37 37]
 [12 50]
 [38 35]
 [17 17]
 [56  7]
 [37 37]
 [ 8  8]
 [60 60]
 [83 22]
 [28 28]
 [24 19]
 [50 50]
 [72 72]
 [24 24]
 [74 74]
 [ 8  8]
 [34 34]
 [ 9 53]
 [16 34]
 [38 45]
 [26 73]
 [ 8  8]
 [ 3 59]
 [22 75]
 [49 50]
 [49 70]
 [60 74]
 [29 20]
 [68 10]
 [37 23]
 [ 4 44]
 [ 9 57]
 [ 9  9]
 [31 31]
 [27 27]
 [13 56]
 [17 66]
 [72 72]
 [51 51]
 [31 31]
 [46 46]
 [65 62]
 [22 22]
 [81 81]
 [74 59]
 [48 48]
 [38 38]
 [27 28]
 [22 22]
 [34 46]
 [22 22]
 [27 51]
 [ 5 20]
 [ 8  8]
 [70 70]
 [ 8  8]
 [59  3]
 [81 81]
 [80 80]
 [18 69]
 [ 3  3]
 [80 80]
 [34  0]
 [80 80]
 [22 49]
 [68 68]
 [ 8  8]
 [62 62]
 [52 37]
 [61 10]
 [10 12]
 [81 10]
 [38 28]
 [30 10]
 [79 66]
 [72 38]
 [75 68]
 [ 6 45]
 [72 72]
 [82 27]
 [81 81]
 [22 22]
 [59 59]
 [35  7]
 [49 49]
 [17 12]
 [65 31]
 [49 70]
 [10 10]
 [33  3]
 [17 17]
 [ 1  1]
 [62 62]
 [ 7  7]
 [18 64]
 [15 35]
 [28 28]
 [26 26]
 [35 69]
 [14 37]
 

## Making the Confusion Matrix

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predknn)
print(cm)
accuracy_score(y_test, y_predknn)



[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.4240506329113924

In [46]:
t, c = 0, 0
print(len(y_test), len(y_predknn))
for y in y_test:
    t += 1
    yp = y_predrfc[list(y_test).index(y)]
    if y == yp:
        c += 1
print(t, c, c/t)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predrfc)
print(cm)

    
accuracy_score(y_test, y_predrfc)

158 158
158 65 0.41139240506329117
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.43037974683544306