# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(X[list(y).index(61), :])
for v in range(len(X[:, 0])):
    X[v, :][0] = conv(X[v, :][0])

print(X[:20, :])


['SrgMD']
[[12470.0]
 [12490.0]
 [12589.0]
 [12590.0]
 [12691.0]
 [12789.0]
 [12792.0]
 [13196.0]
 [13298.0]
 [13308.0]
 [13309.0]
 [13421.0]
 [13431.0]
 [13432.0]
 [13463.0]
 [13513.0]
 [13518.0]
 [13563.0]
 [13587.0]
 [13592.0]]


## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [4]:
print(X_train)

[[35323.0]
 [22011.0]
 [102915.0]
 [109092.0]
 [57314.0]
 [97421.0]
 [86570.0]
 [66221.0]
 [69209.0]
 [97521.0]
 [31478.0]
 [89689.0]
 [16385.0]
 [111570.0]
 [91213.0]
 [36513.0]
 [130911.0]
 [24798.0]
 [85908.0]
 [90842.0]
 [65136.0]
 [109068.0]
 [84691.0]
 [118691.0]
 [69128.0]
 [129797.0]
 [32257.0]
 [58631.0]
 [79212.0]
 [131215.0]
 [80216.0]
 [123307.0]
 [43689.0]
 [32201.0]
 [130887.0]
 [129641.0]
 [108809.0]
 [35692.0]
 [13592.0]
 [73130.0]
 [14791.0]
 [79019.0]
 [68462.0]
 [70690.0]
 [35654.0]
 [58643.0]
 [109097.0]
 [106434.0]
 [35921.0]
 [119648.0]
 [21862.0]
 [58790.0]
 [68641.0]
 [118568.0]
 [43658.0]
 [69086.0]
 [91863.0]
 [70642.0]
 [15908.0]
 [78731.0]
 [68662.0]
 [119641.0]
 [79086.0]
 [112098.0]
 [86878.0]
 [90873.0]
 [78792.0]
 [84621.0]
 [102979.0]
 [58583.0]
 [88811.0]
 [36843.0]
 [108788.0]
 [52689.0]
 [85328.0]
 [36863.0]
 [74325.0]
 [80291.0]
 [86863.0]
 [31632.0]
 [34711.0]
 [59121.0]
 [32989.0]
 [63468.0]
 [91286.0]
 [22186.0]
 [58632.0]
 [46214.0]
 [43468.0]
 

In [5]:
print(y_train)

[72 23 60 45 31 29 58  7 27 74 51 37 27 65 22 81 17 83 27 69 81 80 12 27
 58 49 64 46 74 31  9 56 37 23 22 20 22 34 32 31 50 68 10  4 85  8 45  0
 32 18  7 46 25 82  8 27 52 61 43 70  7 53 46 17 22 70 46 10 49 72 22 37
 22 40 32 28 51 60 28 38 71 19 74 71 58  7 46 10 47 22 51 32 45 22 35 15
 45 31 85 62  3 66 36 66 22 65  9 20 72 63 12 66 13 49 46 11 58 63 22 31
  1 58 62 60 85  4 68 38 26 70 37 58 30 72 63 68 39 83 22 32 47 38 72 73
 71 74 31 12 57 16 62 31  3 38 81 50 56 72  7 27 74 22 10 11  5 68 22 10
  7 12 27 73 22 62  9 11 72 24 74 72 49 16 51 58  3 19 45 23  9 27 56  7
 58  0 10  3 22 23  3 72 60 61 31 10 54 11 45 22 49 58 32 34 41  0  2 43
 63 78 27  1 14 41 63 47 28 72 14 17 22 34  7 38  0 32 34 22  5  7 31 72
 32 58 46 43  3 42 60 46 28 27 55 35 25 34 49 27 46  3 28 20 72 22 31 71
 54 10 63 51 24 31 72 67 75 35 80 30 55 47 33 35 67 26 55 79 73 81  0 68
 27 69 31 74 51 74  6 13 73 58 22 34  3 22 61  0 51  8 18 23 24 72  1 31
 20  9 13 37 53 19  9 51 31 63 72 68 58 74 54 53 63

In [6]:
print(X_test)

[[90906.0]
 [107531.0]
 [89878.0]
 [112096.0]
 [22320.0]
 [71112.0]
 [75316.0]
 [112101.0]
 [90119.0]
 [112102.0]
 [12789.0]
 [70865.0]
 [103029.0]
 [52208.0]
 [47930.0]
 [42490.0]
 [88809.0]
 [119684.0]
 [64891.0]
 [21964.0]
 [87515.0]
 [90213.0]
 [129802.0]
 [121906.0]
 [22317.0]
 [87865.0]
 [111364.0]
 [13298.0]
 [119901.0]
 [123298.0]
 [13463.0]
 [90653.0]
 [65787.0]
 [120113.0]
 [109095.0]
 [58912.0]
 [108436.0]
 [63920.0]
 [64632.0]
 [88086.0]
 [52792.0]
 [87525.0]
 [70653.0]
 [111248.0]
 [120636.0]
 [15689.0]
 [108637.0]
 [66621.0]
 [36463.0]
 [79797.0]
 [22992.0]
 [59130.0]
 [86421.0]
 [112822.0]
 [102922.0]
 [87421.0]
 [80751.0]
 [57121.0]
 [27521.0]
 [130874.0]
 [120880.0]
 [72230.0]
 [15802.0]
 [97979.0]
 [120856.0]
 [107525.0]
 [109063.0]
 [47432.0]
 [130908.0]
 [93022.0]
 [35343.0]
 [106414.0]
 [21985.0]
 [85332.0]
 [109096.0]
 [21984.0]
 [35912.0]
 [108756.0]
 [85324.0]
 [31570.0]
 [122285.0]
 [57312.0]
 [52589.0]
 [15631.0]
 [47029.0]
 [46918.0]
 [80887.0]
 [128656.0]
 [

In [7]:
print(y_test)

[80 66 68 17 63 61 55 17  1 17 74 58 60 43 51 69 22 37 18 53  3 47 49 81
 63 22 23 74 37 64 71 24 55 10 45 15  8 54 23 22 74 64 65 69 28 59 76  7
 23 49 57 19 25 58 60 50 33 13 74 51 22 63 60 49 17 56 80 51 17 72 34  5
 15 32 45 14 19 85 32 65 32 31 15 31 20 25 22 58 58 19 28 58 63 10 46 36
 68 31 32 28  3 27 72 22  4 72 22 23 46 32 70 63 70 28 41 45 27 24 27 24
 75  3 24  9  8 63 42 62 75 23  0 28 68 28 22 63 69 13 13 27 63 22 11 81
 13 13 63  9 19 54 45 62 10 73 30 10 54 20 27 69 84 74 27 43 85 18 22 27
 68 75 31 58 72 27 80 58 71 28 72 72 57 45 30 22 69 73 23 22  5 72 75 56
 37 72 10 29 55 81 14 11 53 73 61 22 27 13 72 43 80 53 55 74 72 38 63 32
 20 38 45  2 39 31 17 51 81 31 43 70 50 34 29 63 22 22 17 53 47 63 58 75
 40  7 28 31 18 34 71 58 66 43 74 65 45  9 22 27  2 11 37  7  3 50 22 63
 32 79 15 46 14 72 38 10  7 71 70  3 17 31 23  8 66 63  3 65 80 23 31 15
  1 15  7  5 57 45 73 27 63 12]


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train.reshape(-1, 1))
X_test = sc.transform(X_test.reshape(-1, 1))

In [9]:
print(X_train)

[[-1.03398218]
 [-1.42501811]
 [ 0.95151218]
 [ 1.13295967]
 [-0.38800327]
 [ 0.79012761]
 [ 0.4713828 ]
 [-0.12636286]
 [-0.03859128]
 [ 0.79306508]
 [-1.14692788]
 [ 0.56300247]
 [-1.59028015]
 [ 1.20575016]
 [ 0.6077695 ]
 [-0.99902629]
 [ 1.77388613]
 [-1.34315084]
 [ 0.45193675]
 [ 0.59687149]
 [-0.15823441]
 [ 1.13225468]
 [ 0.41618775]
 [ 1.41492736]
 [-0.04097063]
 [ 1.74116272]
 [-1.12404499]
 [-0.3493168 ]
 [ 0.25524379]
 [ 1.78281604]
 [ 0.28473599]
 [ 1.55052095]
 [-0.78823348]
 [-1.12568998]
 [ 1.77318114]
 [ 1.73658027]
 [ 1.12464663]
 [-1.02314292]
 [-1.67232367]
 [ 0.0765869 ]
 [-1.63710341]
 [ 0.24957448]
 [-0.06053417]
 [ 0.00491265]
 [-1.02425915]
 [-0.3489643 ]
 [ 1.13310654]
 [ 1.05488173]
 [-1.01641611]
 [ 1.44303895]
 [-1.42939494]
 [-0.34464622]
 [-0.0552761 ]
 [ 1.41131428]
 [-0.7891441 ]
 [-0.04220436]
 [ 0.62686306]
 [ 0.00350266]
 [-1.60429188]
 [ 0.24111457]
 [-0.05465923]
 [ 1.44283332]
 [ 0.25154258]
 [ 1.22126   ]
 [ 0.4804302 ]
 [ 0.59778211]
 [ 0.24290

In [10]:
print(X_test)

[[ 0.59875147]
 [ 1.08710577]
 [ 0.56855429]
 [ 1.22120125]
 [-1.41594133]
 [ 0.01730877]
 [ 0.14079998]
 [ 1.22134813]
 [ 0.57563359]
 [ 1.2213775 ]
 [-1.69591155]
 [ 0.01005322]
 [ 0.9548609 ]
 [-0.53799046]
 [-0.6636554 ]
 [-0.82345374]
 [ 0.53715274]
 [ 1.44409644]
 [-0.16543121]
 [-1.42639872]
 [ 0.49914188]
 [ 0.57839481]
 [ 1.7413096 ]
 [ 1.50936701]
 [-1.41602946]
 [ 0.50942303]
 [ 1.19969898]
 [-1.68095983]
 [ 1.45047074]
 [ 1.55025658]
 [-1.676113  ]
 [ 0.59131968]
 [-0.13911148]
 [ 1.45669818]
 [ 1.13304779]
 [-0.34106251]
 [ 1.11368987]
 [-0.19395404]
 [-0.17303925]
 [ 0.51591483]
 [-0.52083564]
 [ 0.49943563]
 [ 0.00382578]
 [ 1.19629151]
 [ 1.47206114]
 [-1.61072493]
 [ 1.11959418]
 [-0.11461299]
 [-1.00049503]
 [ 0.27242799]
 [-1.39620154]
 [-0.33465882]
 [ 0.46700597]
 [ 1.24252728]
 [ 0.9517178 ]
 [ 0.49638066]
 [ 0.30045145]
 [-0.39367259]
 [-1.26316355]
 [ 1.77279927]
 [ 1.47922857]
 [ 0.05014968]
 [-1.60740559]
 [ 0.80651869]
 [ 1.47852358]
 [ 1.08692952]
 [ 1.13210

## Training the K-NN model on the Training set

In [11]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 9, metric = 'minkowski', p = 2)
knn.fit(X_train.reshape(-1, 1), y_train.reshape(-1, 1))

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 1000, criterion = 'entropy', random_state = 0)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

## Predicting a new result

In [12]:
def conv(phrase):
    t = 0
    multiplier = 10 ** (len(phrase) - 1)
    notes = ['','S','r','R','g','G','M','m','P','d','D','n','N']
    for n in phrase:
        t += notes.index(n) * multiplier
        multiplier /= 10
    return t
print(rfc.predict(sc.transform([[conv('gMP')]])))
print(knn.predict(sc.transform([[conv('SgMdNS')]])))

[61]
[17]


## Predicting the Test set results

In [13]:
y_predknn = knn.predict(X_test)
print(np.concatenate((y_predknn.reshape(len(y_predknn),1), y_test.reshape(len(y_test),1)),1))

y_predrfc = rfc.predict(X_test)
print(np.concatenate((y_predrfc.reshape(len(y_predrfc),1), y_test.reshape(len(y_test),1)),1))

[[17 80]
 [63 66]
 [37 68]
 [17 17]
 [63 63]
 [58 61]
 [ 9 55]
 [17 17]
 [68  1]
 [17 17]
 [34 74]
 [58 58]
 [49 60]
 [38 43]
 [ 0 51]
 [41 69]
 [22 22]
 [68 37]
 [38 18]
 [23 53]
 [ 9  3]
 [68 47]
 [20 49]
 [63 81]
 [63 63]
 [16 22]
 [ 1 23]
 [34 74]
 [68 37]
 [49 64]
 [34 71]
 [ 4 24]
 [ 9 55]
 [68 10]
 [45 45]
 [46 15]
 [70  8]
 [27 54]
 [ 8 23]
 [22 22]
 [11 74]
 [ 9 64]
 [58 65]
 [ 1 69]
 [22 28]
 [58 59]
 [70 76]
 [ 7  7]
 [ 8 23]
 [60 49]
 [13 57]
 [27 19]
 [25 25]
 [63 58]
 [49 60]
 [ 9 50]
 [60 33]
 [31 13]
 [35 74]
 [17 51]
 [22 22]
 [31 63]
 [31 60]
 [74 49]
 [22 17]
 [63 56]
 [45 80]
 [ 0 51]
 [17 17]
 [ 3 72]
 [72 34]
 [28  5]
 [23 15]
 [32 32]
 [45 45]
 [23 14]
 [32 19]
 [70 85]
 [32 32]
 [38 65]
 [49 32]
 [31 31]
 [11 15]
 [58 31]
 [62 20]
 [62 25]
 [60 22]
 [72 58]
 [25 58]
 [72 19]
 [27 28]
 [58 58]
 [11 63]
 [ 1 10]
 [46 46]
 [ 1 36]
 [16 68]
 [31 31]
 [32 32]
 [27 28]
 [31  3]
 [17 27]
 [ 3 72]
 [22 22]
 [26  4]
 [72 72]
 [17 22]
 [ 8 23]
 [27 46]
 [ 3 32]
 [22 70]
 

## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_predknn)
print(cm)
accuracy_score(y_test, y_predknn)



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


0.20469798657718122

In [15]:
t, c = 0, 0
print(len(y_test), len(y_predknn))
for y in y_test:
    t += 1
    yp = y_predrfc[list(y_test).index(y)]
    print(y, yp)
    if y == yp:
        c += 1
print(t, c, c/t)

298 298
80 17
66 56
68 47
17 17
63 63
61 65
55 9
17 17
1 68
17 17
74 74
58 58
60 41
43 43
51 57
69 61
22 22
37 18
18 0
53 53
3 3
47 59
49 49
81 45
63 63
22 22
23 28
74 74
37 18
64 56
71 34
24 24
55 9
10 23
45 45
15 15
8 43
54 27
23 28
22 22
74 74
64 56
65 65
69 61
28 61
59 16
76 12
7 7
23 28
49 49
57 68
19 19
25 25
58 58
60 41
50 83
33 66
13 65
74 74
51 57
22 22
63 63
60 41
49 49
17 17
56 33
80 17
51 57
17 17
72 74
34 24
5 61
15 15
32 32
45 45
14 30
19 19
85 75
32 32
65 65
32 32
31 31
15 15
31 31
20 20
25 25
22 22
58 58
58 58
19 19
28 61
58 58
63 63
10 23
46 46
36 21
68 47
31 31
32 32
28 61
3 3
27 42
72 74
22 22
4 4
72 74
22 22
23 28
46 46
32 32
70 22
63 63
70 22
28 61
41 41
45 45
27 42
24 24
27 42
24 24
75 32
3 3
24 24
9 9
8 43
63 63
42 43
62 10
75 32
23 28
0 8
28 61
68 47
28 61
22 22
63 63
69 61
13 65
13 65
27 42
63 63
22 22
11 11
81 45
13 65
13 65
63 63
9 9
19 19
54 27
45 45
62 10
10 23
73 48
30 30
10 23
54 27
20 20
27 42
69 61
84 24
74 74
27 42
43 43
85 75
18 0
22 22
27 42
68 47
75

## Visualising the Training set results

In [16]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

IndexError: index 1 is out of bounds for axis 1 with size 1

## Visualising the Test set results

In [17]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 1),
                     np.arange(start = X_set[:, 0].min() - 1000, stop = X_set[:, 0].max() + 1000, step = 1))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('K-NN (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

MemoryError: Unable to allocate 106. GiB for an array with shape (120419, 118439) and data type float64